version: "2"
services:
  drupal:
    env_file: .env
    build: .
    volumes:
      - "./app/modules:/var/www/html/modules"
      - "./app/themes:/var/www/html/themes"
      - "./app/settings/settings.php:/var/www/html/sites/default/settings.php"
    ports:
      - "80:80"
    links:
      - db
    restart: always
  db:
    env_file: .env
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
